# Generated by Django 4.2.11 on 2025-12-12 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='vocabulary',
            name='api_vocabul_categor_7492ae_idx',
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['teacher'], name='api_vocabul_teacher_bdb256_idx'),
        ),
        migrations.AddField(
            model_name='category',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='api.category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'teacher')},
        ),
    ]
